services:
  - type: web
    name: frendi-chat-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.4
    healthCheckPath: /
    autoDeploy: true 